patuwwy/ShaderToy-Chrome-Plugin

.gitignore
LICENSE.md
contentscript.js
lib/jszip-3.1.5.js
lib/node-sanitize-filename.js
manifest.json
popup.html
popup.js
shadertoy-plugin-home.js
shadertoy-plugin.js

This adds a one-click ZIP download.  The ZIP includes the JSON file, and also a readme.txt with the title, description, and tags.
Reason: to more easily upload ZIPs to scene.org.  I can hit "Export ZIP" and have a file ready to upload, unless the readme needs hand-tweaking.
I also added a license file, since I pulled in JSZip and node-sanitize-filename.  See also #46.
Thanks for considering this request!

Download shader as a ZIP including a readme.txt

---

app/manifest.json

Reorganized buttons - release.

---

CHANGELOG.md
README.md
app/manifest.json
app/shadertoy-plugin.js
app/style.css

Image preview

---

CHANGELOG.md
app/manifest.json
app/shadertoy-plugin-common.js
app/shadertoy-plugin-profile.js
app/shadertoy-plugin.js

Signed-off-by: Patryk Falba <p.falba@samsung.com>

Hot fixes for Shadertoy update

---

CHANGELOG.md
README.md
app/manifest.json
app/style.css

Fix iMouse sliders on Firefox

---

app/shadertoy-plugin.js

Fix class syntax for firefox

---

app/contentscript.js
app/popup.html
app/popup.js
app/shadertoy-plugin-common.js
app/shadertoy-plugin-profile.js
app/shadertoy-plugin.js
app/style.css

+ some layout tweaks
+ move shaders tiles (alternative profile page) up

Extension internal communication simplified

---

app/contentscript.js

Fix chrome/firefox event access

---

CHANGELOG.md
README.md
app/manifest.json

Bump to 0.13.190

---

app/shadertoy-plugin.js

Fix GPU timers for 'New' shader

---

app/manifest.json

Bump to 0.13.198

---

app/shadertoy-plugin.js

Signed-off-by: patu <patuwwy@gmail.com>

Fix getting webgl2 context for timers

---

CHANGELOG.md
app/manifest.json
app/shadertoy-plugin.js

fix for resolution decrease

---

README.md

Update beers count

---

app/manifest.json
app/shadertoy-plugin.js

Fix shader forking

---

app/manifest.json
app/shadertoy-plugin.js

Purge passes on import/fork

---

app/manifest.json
app/shadertoy-plugin.js

Change exportToJSON to Save

---

app/manifest.json
app/shadertoy-plugin.js

fix export to zip

---

app/add-ons/shadertoy-plugin-bbcode.js
app/manifest.json

No BB buttons attaching if no comment area exists

---

app/manifest.json
app/shadertoy-plugin.js
app/style.css

Add MonacoEditor (Issue #164)

---

CHANGELOG.md
app/background.js
app/manifest.json
app/shadertoy-plugin.js

Compilation errors

---

app/add-ons/shadertoy-plugin-parameters.js
app/contentscript.js
app/manifest.json

This pull request adds support for shader parameters to the code. So far only textures by URL or base64.

"Add support for shader parameters"

---

app/shadertoy-plugin-common.js
app/style.css

Add feature to issue https://github.com/patuwwy/ShaderToy-Chrome-Plugin/issues/94
Now you can create a new shader template when clicking "New"

Add feature: shader template
